[improve][function] Add API endpoints for function-worker for liveness checks with configurable flags
datastax/pulsar pull request #358
Opened 2024-12-31 11:26 UTC by mukesh-ctds

### Motivation
This pull request implements new health check functionality for Kubernetes deployment, focusing on the liveness probe for function worker. This liveliness API is required for Kubernetes-based applications, enabling automated pod restarts in case of failure (via liveness checks) whenever ProducerFencedException occurs.

### Modifications

This update introduces an API endpoint to perform a liveliness check on the function worker pod. The API returns an HTTP status of `200 (OK)` when the `isLive` flag within `FunctionImpl` is true. If the flag is false, typically after a `ProducerFencedException` occurs, the API will return a status of `503 (Service Unavailable)`.

The Kubernetes deployment configuration has been updated to use this new API endpoint in the liveness probe along with existing `metrics` endpoint, allowing the system to monitor the health and availability of the function worker.

### Verifying this change

- [X] Make sure that the change passes the CI checks.

*(Please pick either of the following options)*

This change is a trivial rework / code cleanup without any test coverage.

### Does this pull request potentially affect one of the following parts:

*If `yes` was chosen, please highlight the changes*

  - Dependencies (does it add or upgrade a dependency): (no)
  - The public API: (no)
  - The schema: (no)
  - The default values of configurations: (no)
  - The wire protocol: (no)
  - The rest endpoints: (no)
  - The admin cli options: (no)
  - Anything that affects deployment: (no)

### Documentation

Check the box below or label this PR directly (if you have committer privilege).

Need to update docs? 

- [ ] `doc-required` 
- [X] `no-need-doc` 
- [ ] `doc`

2025-01-02 17:15 UTC, pgier requested changes

2025-01-02 17:15 UTC, pgier commented on pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v3/FunctionsApiV3Resource.java
> +    @Path("/live")
I think `/healthz` is the common convention for this endpoint name.
Also, I think it would make more sense to put it directly under the root path instead of under `/admin/v3/functions`.

2025-01-02 17:15 UTC, pgier commented on pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java
> +            log.error("Function worker status has been set to false due to ProducerFencedException.");
What happens here if we get an `IllegalStateException` which is not a `ProducerFencedException`?  Maybe it would be better to catch the specific exception type.

2025-01-03 10:16 UTC, mukesh-ctds commented on pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/v3/FunctionsApiV3Resource.java
> +    @Path("/live")
The API has been updated to include a `/healthz` endpoint. 
We cannot place this directly under the root path, as the root path does not have access to the necessary flag. The flag is available at the function level instead. Additionally, v2 does not contain any logic that could trigger a ProducerFencedException; this issue is specific to v3.

2025-01-03 10:17 UTC, mukesh-ctds commented on pulsar-functions/worker/src/main/java/org/apache/pulsar/functions/worker/rest/api/FunctionsImpl.java
> +            log.error("Function worker status has been set to false due to ProducerFencedException.");
The block of code has been moved to a location where we can check if the cause is a `ProducerFencedException`.

2025-01-08 16:13 UTC, pgier approved these changes
LGTM, can you also create an upstream PR?

2025-01-13 04:46 UTC, srinath-ctds approved these changes

2025-01-13 04:47 UTC, merged