[feat][elasticsearch-sink] Option to output canonical JSON
datastax/pulsar pull request #69
Opened 2022-04-12 14:12 UTC by nicoloboschi

2022-04-12 15:03 UTC, eolivelli requested changes
overall LGTM

I left one comment about the test

2022-04-12 15:23 UTC, cbornet commented on pulsar-io/elastic-search/src/test/java/org/apache/pulsar/io/elasticsearch/ElasticSearchExtractTests.java
> +            RecordSchemaBuilder keySchemaBuilder = org.apache.pulsar.client.api.schema.SchemaBuilder.record("key");
Can this go to a distinct test with explicit naming explaining the difference of what we are testing.
Also not a big fan of scoping inside functions.

2022-04-14 11:36 UTC, nicoloboschi commented
CI is ok. If you open the job everything passed (except for a couple of flakies and owasp)

2022-04-14 14:05 UTC, eolivelli approved these changes

2022-04-14 14:05 UTC, merged

2022-04-14 17:05 UTC, lhotari reviewed
Good work!