[feat][elasticsearch-sink] Option to string non printable characters
datastax/pulsar pull request #77
Opened 2022-04-27 12:07 UTC by nicoloboschi

- New option `stripNonPrintableCharacters` default=true (which will trigger a different behaviour by default) which removes the non printable characters from the output json (only for the document, not the _id)

2022-04-27 12:10 UTC, eolivelli commented
@nicoloboschi can you please add some references to the problem ? is it a limitation of JSON ?

2022-04-27 12:56 UTC, eolivelli requested changes
the patch looks good but please note that enabling this by default may add a small bigger resource consumption (both CPU and memory), I have added a comment

2022-04-27 17:29 UTC, lhotari commented on pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
> +    private final Pattern nonPrintableCharactersPattern = Pattern.compile("[\\p{C}]");
Could you add a comment with the reference for this pattern?

2022-04-27 17:30 UTC, lhotari commented on pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
> +    private final Pattern nonPrintableCharactersPattern = Pattern.compile("[\\p{C}]");
btw. with Googling I found https://stackoverflow.com/questions/44034232/undocumented-java-regex-character-class-pc .

2022-04-28 03:35 UTC, lhotari approved these changes

2022-04-28 07:32 UTC, eolivelli commented on pulsar-io/elastic-search/src/main/java/org/apache/pulsar/io/elasticsearch/ElasticSearchSink.java
> +        return nonPrintableCharactersPattern.matcher(value).replaceAll("");
makes sense

2022-04-28 07:32 UTC, eolivelli approved these changes
LGTM

2022-04-28 07:42 UTC, merged